import Head from 'next/head'
import Header from '../components/Header'
import Hero from '../components/Hero'
import InfoHeader from '../components/InfoHeader'
import Categories from '../components/Categories'
import Footer from '../components/Footer'
import Products from '../components/Products'
import AOS from 'aos'
import 'aos/dist/aos.css'
import { useEffect } from 'react'

export default function Home({products}) {

  useEffect(() =>{
    AOS.init({duration:2000});
  },[])

  
  return (
    <div className='relative flex'>
    <div>
      <Head>
        <title>Egerton Comrades In Business</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/my-logo.png" />
      </Head>
      <InfoHeader />
      <Header />
      <Hero />
      <main className=' max-w-screen-2xl mx-auto'>
      <Categories /> 
      <Products products ={products} />
      </main>
      <Footer />   
     </div>
     <div className='hidden sticky bg-slate-50 z-50 right-0 top-0 z-100 w-1/4 h-[100vh]'>
       <p>Hello</p>
     </div>
    </div>
  )
}

export async function getServerSideProps(){
  const products = await fetch('https://fakestoreapi.com/products').then(res => res.json());

  return{
    props:{
      products
    }
  }
}