import Head from 'next/head'
import Header from '../components/Header'
import Hero from '../components/Hero'
import InfoHeader from '../components/InfoHeader'

import Footer from '../components/Footer'
import Products from '../components/Products'


export default function Home({products}) {
  return (
    <div>
      <Head>
        <title>Egerton Comrades In Business</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/favicon-16x16.png" />
      </Head>
      <InfoHeader />
      <Header />
      <Hero />
      <main className=' max-w-screen-2xl mx-auto'>
          <Products products ={products} />
      </main>
      <Footer />
    </div>
  )
}

export async function getServerSideProps(){
  const products = await fetch('https://fakestoreapi.com/products').then(res => res.json());

  return{
    props:{
      products
    }
  }
}