import React from 'react'
import Image from 'next/image'
import Head from 'next/head'
import Header from '../components/Header'
import { useRouter } from 'next/router'
import Footer from '../components/Footer'
function Liked() {
    const router = useRouter();

  return (
  <div>
     <Head>
        <title>ECIB-Favorites</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/favicon-16x16.png" />
    </Head>
    <Header />
        <div className='flex items-center justify-center'>
        <div className='flex flex-col bg-white mt-20 min-w-[300px] mx-10 w-full  md:w-1/2'>
            <h1 className=' text-center text-2xl font-semibold py-5'>You have no favorites!</h1>
            <Image src='/images/no-favorites.png' width={300}  height={300} objectFit='contain' />
            <button onClick={() => router.push('/')} className='cartButton'>Back to Home</button>
        </div>
    </div>
    <Footer />
 </div>
  )
}

export default Liked